In [1]:
import numpy as np
import pandas as pd
f = open("day_13_input.txt")
[timestamp, raw_input_string] = f.read().split("\n")
input_array = np.array(raw_input_string.split(","))

In [2]:
def day_13_part_1():
    bus_ids = input_array[input_array != "x"].astype(int)
    timestamp_int = int(timestamp)
    
    modulus_time = bus_ids - (timestamp_int % bus_ids)
    return modulus_time.min() * bus_ids[modulus_time.argmin()]

In [3]:
day_13_part_1()

2947

In [5]:
np.arange(0, len(input_array))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61])

In [17]:
index_array = np.where(input_array != "x")[0]
parsed_array = input_array[index_array].astype(int)
index_array, parsed_array

(array([ 0,  3,  7, 13, 32, 36, 42, 44, 61], dtype=int64),
 array([ 13,  41,  37, 419,  19,  23,  29, 421,  17]))

In [15]:
i = 0
while True:
    i += parsed_array[0]
    for idx, val in zip(index_array, parsed_array):
        if i % val

array([ 0,  3,  7, 13, 32, 36, 42, 44, 61], dtype=int64)